### PR TITLE
T01.01-Solution-CreateLayout

### PR DESCRIPTION
**Pull request by omargnagy**
<?xml version="1.0" encoding="utf-8"?>

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"

    android:layout_width="match_parent"
    android:layout_height="match_parent">

    
    
    
    
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        android:textSize="20sp"
        android:padding="16dp"
        />

</FrameLayout>

### CODE REVIEW

**Comment by axw9973** [comment]
1. Change the constraint layout to frame layout
2. Remove the constraint layout attributes
3. Modify the textView's size

**Comment by AstrideDjuikom** [comment]
Easy i like it

**Comment by JaymK** [comment]
Complete. Easy.

**Comment by johnshea** [comment]
PR is requesting we merge changes from later lesson branches into earlier lesson branches.

We will not be doing this as these branches are set-up this way on purpose for the course.

**Pull request closed without merging**
