### PR TITLE
T02.05-Solution-CreateAsyncTask

### PR DESCRIPTION
**Pull request by egmp777**
Finished successfully

### CODE REVIEW

**Comment by marwan2018** [comment]
Done

**Comment by JaymK** [comment]
Done

**Comment by gleideveloper** [comment]
Done!

**Comment by johnshea** [comment]
PR is requesting we merge changes from later lesson branches into earlier lesson branches.

We will not be doing this as these branches are set-up this way on purpose for the course.

**Comment by ILyaCyclone** [comment]
https://github.com/udacity/ud851-Exercises/pull/83/commits/fced92bee8f99bed62ee032a871dde553a0877fb#diff-9a36df2b648dab135881c2f9f20a64daR83
Isn't `s.length()==0` more efficient than `!s.equals("")`?

**Pull request closed without merging**
