### PR TITLE
T2.06-AddPolish AND T04b.02-Solution-OpenMap Fixes

### PR DESCRIPTION
**Pull request by mrk-han**
Hello Udacity,

I came across a small visual bug when testing the completed T2.06-Exercise.  

**Str:**
1) Query "Android" (Or any valid first search that returns JSON)
2) Hit Search
3) JSON Displays
4) Query "Udacity" (Or any valid second search)

**Expected**: Spinner for ProgressBar hovers over blank search result view
**Actual**: Spinner for ProgressBar hovers over a big JSON file from previous search

This fix ensures that when a user conducts at least 2 searches, that they do not see the previous results while trying to view the ProgressBar for the second search.  Having the ProgressBar show up over the JSON is pretty ugly.  😄 I believe that adding TODO (28) will fix this visual bug, and is especially appropriate in the lesson titled "Add Polish". 

Thanks!
Mrk-Han

cc:
@ceruleanotter 

PS: 
I know you guys aren't super actively maintaining this repo, but I do think this change would be worth it. 😃 Also, thanks for all the awesome videos!

### CODE REVIEW

**Comment by mrk-han** [comment]
t2 06-addpolish-add todo 28
A GIF of the proposed final solution.

**Comment by mrk-han** [comment]
Another great way to achieve the same thing would be to add 
`mSearchResultsTextView.setText("");` before `makeGithubSearchQuery();` is called in `onOptionsItemSelected(MenuItem item)`

SEE BELOW

```
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int itemThatWasClickedId = item.getItemId();
        if (itemThatWasClickedId == R.id.action_search) {
            mSearchResultsTextView.setText("");
            makeGithubSearchQuery();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
```

**Comment by mrk-han** [comment]
Tacked on a fix for T04b.02-Solution-OpenMap

This fix allows the addressString to successfully send to Google Maps.

```
        // COMPLETED (6) Use Uri.Builder with the appropriate scheme and query to form the Uri for the address
        Uri.Builder builder = new Uri.Builder();
        builder.scheme("geo")
                .path("0,0")
                .query(addressString);
        Uri addressUri = builder.build();
``` 
Above code was not working, so changed to
```
        // COMPLETED (6) Use Uri.Builder with the appropriate scheme and query to form the Uri for the address
        Uri.Builder builder = new Uri.Builder();
        builder.scheme("geo")
                .path("0,0")
                .appendQueryParameter("q", addressString);
        Uri addressUri = builder.build();
```

**Comment by mrk-han** [comment]
bump

**Comment by johnshea** [comment]
T2.06: Cosmetic change to UI. Will not be implementing at this time.

T04b.02: Fixed.

**Comment by mrk-han** [comment]
Cool, thanks for the follow up! @johnshea

**Pull request closed without merging**
